name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --prefix app

    - name: Build Docker image
      run: docker build -t ${{ Secrets.DOCKER_USERNAME }}/devops-app:latest -f docker/Dockerfile .

    - name: Push Docker image
      run: |
        echo ${{ Secrets.DOCKER_PASSWORD }} | docker login -u ${{ Secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ Secrets.DOCKER_USERNAME }}/devops-app:latest

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/
